---
- name: Check firewalld status
  shell: "systemctl show firewalld | grep UnitFileState"
  register: firewalld_status
  failed_when: false
  changed_when: false

- name: Open ports for Grafana
  firewalld:
    port: "{{ item }}"
    zone: "{{ ceph_dashboard_firewall_zone }}"
    state: enabled
    immediate: true
    permanent: true
  with_items:
    - 3000/tcp
  when: "'enabled' in firewalld_status.stdout"
